version: '3.1'
services:
  db:
    image: postgres:11
    container_name: postgres-container
    ports:
      - 25432:5432
    environment:
      - POSTGRES_DB=bank_app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  